import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { GoogleGenAI } from '@google/genai';

function getFiles(dir: string, fileList: string[] = []): string[] {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      getFiles(filePath, fileList);
    } else if (filePath.endsWith('.ts') || filePath.endsWith('.tsx')) {
      fileList.push(filePath);
    }
  }
  return fileList;
}

async function improve(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Exiting ai-improve without error.');
    process.exit(0);
  }

  try {
    const directories = ['src', 'api', 'scripts'];
    let allFiles: string[] = [];

    for (const dir of directories) {
      allFiles = allFiles.concat(getFiles(dir));
    }

    // Prioritize core files, random sample others to avoid context limit
    const coreFiles = allFiles.filter(
      (f) =>
        f.includes('analyze-core') ||
        f.includes('mcp-tools') ||
        f.includes('server.ts') ||
        f.includes('automation'),
    );
    const otherFiles = allFiles.filter((f) => !coreFiles.includes(f));

    // Simple random sampling for non-core files to keep prompt manageable
    const sampledOthers = otherFiles.sort(() => 0.5 - crypto.randomBytes(1)[0] / 255).slice(0, 10);
    const selectedFiles = [...coreFiles, ...sampledOthers];

    let codeContext = '';
    for (const file of selectedFiles) {
      codeContext += `\n--- ${file} ---\n`;
      codeContext += fs.readFileSync(file, 'utf-8');
    }

    const ai = new GoogleGenAI({ apiKey });

    const prompt = `
    You are an expert AI maintainer for the Intelli-Credit Terminal open-source repository.
    Your task is to analyze the codebase and identify areas for continuous improvement.
    Look for: technical debt, documentation gaps, security risks, performance issues, and architectural concerns.

    Here is a sample of the codebase:
    ${codeContext}

    Generate a detailed Markdown report outlining your findings and actionable recommendations for improvement.
    Focus on high-impact changes.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const report = response.text;
    if (report) {
      const outDir = 'docs/history';
      fs.mkdirSync(outDir, { recursive: true });

      const timestamp = new Date().toISOString().split('T')[0];
      const outPath = path.join(outDir, `ai-improvement-report-${timestamp}.md`);

      fs.writeFileSync(outPath, report);

      // Also write to a static file name for the GitHub Action to easily pick up and create an issue
      fs.writeFileSync(path.join(outDir, 'ai-improvement-report.md'), report);
      console.info('Improvement report generated successfully.');
    } else {
      console.warn('No response text generated by Gemini.');
    }
  } catch (err) {
    console.error('Error during AI improvement loop:', err);
    process.exit(1);
  }
}

void improve();
