import * as fs from 'node:fs';
import * as path from 'node:path';
import { GoogleGenAI } from '@google/genai';

function getFiles(dir: string, fileList: string[] = []): string[] {
  const excludeDirs = ['node_modules', '.git', 'dist', 'coverage', '.github'];

  if (!fs.existsSync(dir)) return fileList;

  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      if (!excludeDirs.includes(file)) {
        getFiles(filePath, fileList);
      }
    } else {
      if (file.endsWith('.ts') || file.endsWith('.tsx') || file.endsWith('.json')) {
        fileList.push(filePath);
      }
    }
  }
  return fileList;
}

async function improve() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    process.stderr.write('GEMINI_API_KEY environment variable is missing.\n');
    process.exit(1);
  }

  const crypto = await import('node:crypto');
  const allFiles = getFiles('.');
  // Sample up to 10 random files to avoid context limits
  const sampleFiles = allFiles.sort(() => 0.5 - crypto.randomBytes(1)[0] / 255).slice(0, 10);

  let codebaseContext = '';
  for (const file of sampleFiles) {
    try {
      const content = fs.readFileSync(file, 'utf8');
      codebaseContext += `\n\n--- File: ${file} ---\n${content}\n`;
    } catch {
      // Ignore read errors
    }
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `You are a world-class AI maintainer continuously analyzing the 'intelli-credit' open-source repository.

Review the following randomly sampled codebase files to detect technical debt, documentation gaps, potential bugs, performance issues, or structural improvements.

Codebase Sample:
${codebaseContext}

Generate a "Daily AI Improvement Report". It should include:
1. Executive Summary of findings.
2. High-priority Action Items (e.g., refactoring opportunities, security flags).
3. Suggested documentation improvements.
4. Specific code snippets showing how to implement the improvements.

Format the output strictly as a Markdown document.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    const aiResponse = response.text;
    if (aiResponse) {
      const outputDir = path.join('docs', 'history');
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      fs.writeFileSync(path.join(outputDir, 'ai-improvement-report.md'), aiResponse, 'utf8');
      process.stdout.write('AI Improvement Report generated successfully.\n');
    } else {
      process.stderr.write('No response generated by Gemini.\n');
      process.exit(1);
    }
  } catch (error) {
    process.stderr.write(
      `Failed to generate improvement report: ${error instanceof Error ? error.message : 'Unknown error'}\n`,
    );
    process.exit(1);
  }
}

await improve().catch((err) => {
  process.stderr.write(
    `Unexpected error: ${err instanceof Error ? err.message : 'Unknown error'}\n`,
  );
  process.exit(1);
});
