import fs from 'node:fs';
import path from 'node:path';
import { GoogleGenAI } from '@google/genai';

function getFiles(dirPath: string): string[] {
  const files: string[] = [];
  try {
    const items = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const item of items) {
      if (item.name === 'node_modules' || item.name === 'dist' || item.name === '.git') continue;
      const fullPath = path.join(dirPath, item.name);
      if (item.isDirectory()) {
        files.push(...getFiles(fullPath));
      } else if (fullPath.endsWith('.ts') || fullPath.endsWith('.tsx')) {
        files.push(fullPath);
      }
    }
  } catch (e) {
    // ignore
  }
  return files;
}

async function improve() {
  if (!process.env.GEMINI_API_KEY) {
    console.warn('GEMINI_API_KEY not found. Skipping AI Continuous Improvement.');
    process.exit(0);
  }

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

  let repoContext = '';
  const directoriesToScan = ['src', 'api', 'scripts'];
  for (const dir of directoriesToScan) {
    const files = getFiles(dir);
    for (const file of files) {
      try {
        const content = fs.readFileSync(file, 'utf8');
        repoContext += `\n--- File: ${file} ---\n${content}\n`;
      } catch (e) {
        console.error(`Failed to read ${file}`, e);
      }
    }
  }

  const prompt = `You are a Principal Engineer analyzing the codebase to identify areas for improvement.
Review the following codebase files and generate a continuous improvement report.
Focus on identifying technical debt, code smells, missing documentation, potential security vulnerabilities, performance optimizations, and architectural enhancements.

Format your response as a Markdown document with clear sections for each category. Provide actionable recommendations.

Codebase Context:
${repoContext.substring(0, 100000)} // truncate to avoid hitting context limits, though flash handles a lot
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const report = response.text;
    if (report) {
      fs.writeFileSync('ai-improvement-report.md', report, 'utf8');
      console.info('Generated AI improvement report successfully.');
    } else {
      console.error('No text generated by Gemini API.');
    }
  } catch (err) {
    console.error('Error during AI improvement analysis:', err);
    process.exit(1);
  }
}

void improve();
