import { GoogleGenAI } from '@google/genai';
import * as fs from 'node:fs';

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.warn('GEMINI_API_KEY is not set. Skipping AI PR Review.');
  process.exit(0);
}

const ai = new GoogleGenAI({ apiKey });

async function reviewPR() {
  try {
    let prDiff = '';
    try {
      prDiff = fs.readFileSync('pr-diff.txt', 'utf8');
    } catch (e) {
      console.warn('Could not read pr-diff.txt. Ensure it was generated by the workflow.');
      process.exit(0);
    }

    if (!prDiff.trim()) {
      console.warn('PR Diff is empty. Nothing to review.');
      process.exit(0);
    }

    const prompt = `You are a strict, senior staff engineer reviewing a pull request for a React/Express application.
Analyze the following git diff and provide constructive, critical feedback.
Focus on:
- Code quality and maintainability
- Security vulnerabilities
- Performance issues
- Adherence to best practices (e.g., React button types, proper promise handling)
If you find issues, provide specific code suggestions. If the PR looks good, say so.

PR Diff:
${prDiff}`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const aiResponseText = response.text;

    if (aiResponseText) {
      fs.writeFileSync('pr-comment.txt', aiResponseText);
      console.info('Successfully generated AI PR review.');
    } else {
      console.error('AI response was empty.');
      process.exit(1);
    }
  } catch (error) {
    console.error('Error during AI PR review:', error);
    process.exit(1);
  }
}

void reviewPR();
