import { GoogleGenAI } from '@google/genai';
import * as fs from 'node:fs';
import { execFileSync } from 'node:child_process';

// AI PR Review script for GitHub PRs

const reviewPr = async (): Promise<void> => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.warn('GEMINI_API_KEY is missing. Skipping AI PR Review.');
      process.exit(0);
    }

    const eventPath = process.env.GITHUB_EVENT_PATH;
    if (!eventPath) {
      console.warn('GITHUB_EVENT_PATH is missing. This script should be run in GitHub Actions.');
      process.exit(0);
    }

    const eventData = JSON.parse(fs.readFileSync(eventPath, 'utf8'));

    if (!eventData.pull_request) {
      console.warn('No pull request data found in event payload.');
      process.exit(0);
    }

    const prUrl = eventData.pull_request.url;

    // Fetch PR diff directly from GitHub API as per memory instructions
    console.info(`Fetching PR diff from ${prUrl}...`);
    let prDiff = '';

    try {
       prDiff = (execFileSync('curl', [
        '-s',
        '-H', `Authorization: token ${process.env.GITHUB_TOKEN || ''}`,
        '-H', 'Accept: application/vnd.github.v3.diff',
        prUrl
      ], { encoding: 'utf-8' }) as string);
    } catch (e) {
       console.error('Failed to fetch diff via curl', e);
       process.exit(1);
    }

    if (!prDiff) {
       console.warn('Empty diff returned, nothing to review.');
       fs.writeFileSync('pr-comment.txt', 'No meaningful changes found in the PR diff.');
       process.exit(0);
    }

    const ai = new GoogleGenAI({ apiKey });

    const prompt = `
      You are a senior staff engineer AI reviewer for the Intelli-Credit project.
      Please review the following Pull Request diff and provide constructive feedback.
      Look for security issues, performance problems, bugs, or architectural concerns.
      If everything looks good, briefly mention that.

      --- PR Diff ---
      ${prDiff}
      ---------------

      Provide your review feedback in markdown format, ready to be posted as a PR comment.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const comment = response.text || 'LGTM! (Generated by AI)';

    // Write comment to file for github actions
    fs.writeFileSync('pr-comment.txt', comment);
    console.info('Successfully generated PR review comment.');

  } catch (error) {
    console.error('Error during AI PR review:', error);
    process.exit(1);
  }
};

reviewPr().catch(err => {
  console.error(err);
  process.exit(1);
});
