import * as fs from 'node:fs';
import { GoogleGenAI } from '@google/genai';

async function reviewPR(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is missing. Skipping AI PR review.');
    process.exit(0);
  }

  const ai = new GoogleGenAI({ apiKey });

  try {
    let diff = '';
    if (fs.existsSync('pr-diff.txt')) {
      diff = fs.readFileSync('pr-diff.txt', 'utf-8');
    } else {
      console.warn('pr-diff.txt not found. Cannot perform PR review.');
      return;
    }

    if (!diff) {
      console.info('No changes found in diff.');
      return;
    }

    const prompt = `
Perform a code review of the following Git diff:

${diff}

Provide your feedback in Markdown format:
1. Summarize the changes briefly.
2. Point out any potential bugs, security issues, or performance concerns.
3. Suggest improvements for maintainability or readability.
4. If everything looks good, say so!
`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const comment = response.text || 'LGTM! (Generated by AI)';
    fs.writeFileSync('pr-comment.txt', comment);
    console.info('PR review comment generated successfully.');
  } catch (error) {
    console.error('Error during AI PR review:', error);
    process.exit(1);
  }
}

void reviewPR();
