import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { GoogleGenAI } from '@google/genai';

const main = async () => {
  console.info('Running AI Documentation Reviewer...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping real AI review generation.');
    fs.writeFileSync(
      path.resolve(process.cwd(), 'ai-review-output.md'),
      'GEMINI_API_KEY is not set. Skipping real AI review generation.',
    );
    return;
  }

  let diff = '';
  try {
    // Attempt to get the diff against main. In a PR, this would be the PR diff.
    diff = execSync('git diff origin/main...HEAD').toString();
    if (!diff) {
      diff = execSync('git show').toString(); // Fallback for testing locally
    }
  } catch (error) {
    console.warn('Could not fetch git diff. Ensure git is initialized and committed.');
    diff = 'No diff available. This might be a new branch or no commits are made.';
  }

  // Example: Read some metadata to give context to the AI
  const metadataPath = path.resolve(process.cwd(), 'metadata.json');
  let metadata: Record<string, unknown> = {};
  if (fs.existsSync(metadataPath)) {
    metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  }

  console.info(`Analyzing diff for ${metadata.name || 'Project'}...`);

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
You are an expert AI software architect and documentation maintainer.
Analyze the following Git diff for a project named ${metadata.name}.

Repository Metadata:
Frameworks: ${metadata.frameworks?.join(', ') || 'Unknown'}

Git Diff:
\`\`\`diff
${diff.substring(0, 50000)} // truncate to avoid token limits
\`\`\`

Tasks:
1. Summarize the changes made in this Pull Request.
2. Detect any architectural modifications (new dependencies, new routes, database changes, etc.).
3. Generate missing documentation strings or identify areas that lack documentation.
4. Assess documentation quality and consistency.
5. Identify any potential security concerns or vulnerabilities introduced in the diff.
6. Identify potential performance regressions.
7. Suggest missing test coverage for the changes.
8. Provide recommendations for the developer to improve code quality or architecture.
9. Generate actionable code fixes in diff format where issues are found.

Remember to act as a senior staff engineer: explain your findings, recommend fixes, and prioritize issues accurately.
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'AI Generation failed due to an API error.';
  }

  const outDir = path.resolve(process.cwd(), 'docs/ai-reviews');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const reviewContent = `# AI Repository Review
Date: ${new Date().toISOString()}
PR Number: ${process.env.PR_NUMBER || 'Manual Run'}

${responseText}
`;

  fs.writeFileSync(path.join(outDir, `review-${Date.now()}.md`), reviewContent);
  // Ensure the file exists for the github action even if no API key is provided
  fs.writeFileSync(path.resolve(process.cwd(), 'ai-review-output.md'), reviewContent);

  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, reviewContent);
  }

  console.info('AI Review generated successfully.');
};

main().catch(console.error);
