import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';

const main = async () => {
  console.info('Running AI Issue Triager...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping real AI triage generation.');
    fs.writeFileSync(
      path.resolve(process.cwd(), 'ai-triage-output.md'),
      'GEMINI_API_KEY is not set. Skipping real AI triage generation.',
    );
    return;
  }

  const issueTitle = process.env.ISSUE_TITLE || 'Unknown Issue Title';
  const issueBody = process.env.ISSUE_BODY || 'No issue body provided.';

  console.info(`Analyzing issue: ${issueTitle}`);

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
You are an expert open-source maintainer and issue triager.
Analyze the following GitHub issue.

Title: ${issueTitle}
Body:
${issueBody}

Tasks:
1. Suggest appropriate GitHub labels for this issue (e.g., bug, enhancement, documentation, question, help wanted). Format as a comma-separated list.
2. Provide an initial, welcoming response to the issue creator. Thank them for their contribution, acknowledge the issue, and provide any immediate guidance or troubleshooting steps if applicable. If more information is needed, ask for it politely.

Format your response exactly as follows:
LABELS: label1, label2
RESPONSE:
[Your welcoming response here]
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'LABELS: triage\nRESPONSE: AI Generation failed due to an API error.';
  }

  const match = responseText.match(/LABELS:\s*(.*?)\s*RESPONSE:\s*([\s\S]*)/i);
  let labels = 'triage';
  let comment = responseText;

  if (match) {
    labels = match[1].trim();
    comment = match[2].trim();
  }

  const outDir = path.resolve(process.cwd(), 'docs/ai-triage');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const triageContent = `### AI Triage Output\n\n**Suggested Labels:** ${labels}\n\n**Suggested Response:**\n${comment}\n`;

  fs.writeFileSync(path.join(outDir, `triage-${Date.now()}.md`), triageContent);
  // Ensure the file exists for the github action
  fs.writeFileSync(path.resolve(process.cwd(), 'ai-triage-output.md'), comment);
  fs.writeFileSync(path.resolve(process.cwd(), 'ai-triage-labels.txt'), labels);

  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, triageContent);
  }

  console.info('AI Triage generated successfully.');
};

main().catch(console.error);
