import * as fs from 'node:fs';
import { GoogleGenAI } from '@google/genai';

async function triage() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    process.stderr.write('GEMINI_API_KEY environment variable is missing.\n');
    process.exit(1);
  }

  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath) {
    process.stderr.write('GITHUB_EVENT_PATH environment variable is missing.\n');
    process.exit(1);
  }

  const eventData = JSON.parse(fs.readFileSync(eventPath, 'utf8')) as Record<string, any>;
  const issue = eventData.issue;

  if (!issue || !issue.title || !issue.body) {
    process.stderr.write('Issue data is missing or incomplete.\n');
    process.exit(0);
  }

  const title = issue.title as string;
  const body = issue.body as string;

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `You are an expert AI maintainer for the 'intelli-credit' open-source project.
An issue has been opened with the title: "${title}"
And the following body:
"""
${body}
"""

Please provide a helpful, welcoming, and technical triage response.
Acknowledge the issue, suggest potential areas in the codebase to investigate if it's a bug, or discuss the feasibility if it's a feature request.
Format your response nicely in Markdown.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    const aiResponse = response.text;
    if (aiResponse) {
      fs.writeFileSync('triage-comment.txt', aiResponse, 'utf8');
      process.stdout.write('Triage comment generated successfully.\n');
    } else {
      process.stderr.write('No response generated by Gemini.\n');
      process.exit(1);
    }
  } catch (error) {
    process.stderr.write(
      `Failed to generate triage response: ${error instanceof Error ? error.message : 'Unknown error'}\n`,
    );
    process.exit(1);
  }
}

await triage().catch((err) => {
  process.stderr.write(
    `Unexpected error: ${err instanceof Error ? err.message : 'Unknown error'}\n`,
  );
  process.exit(1);
});
