import * as fs from 'node:fs';
import { GoogleGenAI } from '@google/genai';

async function triage(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Exiting ai-triage without error.');
    process.exit(0);
  }

  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath || !fs.existsSync(eventPath)) {
    console.error('GITHUB_EVENT_PATH not found or file does not exist.');
    process.exit(1);
  }

  try {
    const eventData = JSON.parse(fs.readFileSync(eventPath, 'utf-8')) as Record<string, unknown>;
    const issue = eventData.issue as Record<string, unknown> | undefined;

    if (!issue) {
      console.warn('No issue found in event payload.');
      process.exit(0);
    }

    const title = issue.title as string;
    const body = issue.body as string;
    const author = (issue.user as Record<string, unknown>).login as string;

    const ai = new GoogleGenAI({ apiKey });

    const prompt = `
    You are an expert AI maintainer for the Intelli-Credit Terminal open-source repository.
    A new issue has been created.

    Title: ${title}
    Body:
    ${body}

    Please provide a helpful, welcoming triage response to the author (@${author}).
    Acknowledge the issue, provide initial thoughts or troubleshooting steps if applicable, and explain that a maintainer will review it soon.
    Output only the message text.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    if (response.text) {
      fs.writeFileSync('triage-comment.txt', response.text);
      console.info('Triage comment generated successfully.');
    } else {
      console.warn('No response text generated by Gemini.');
    }
  } catch (err) {
    console.error('Error during AI triage:', err);
    process.exit(1);
  }
}

void triage();
