import * as fs from 'node:fs';
import * as path from 'node:path';
import { GoogleGenAI } from '@google/genai';

function getFiles(dir: string, fileList: string[] = []): string[] {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      getFiles(filePath, fileList);
    } else if (filePath.endsWith('.ts') || filePath.endsWith('.tsx')) {
      fileList.push(filePath);
    }
  }
  return fileList;
}

async function analyze(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Exiting analyze-repo without error.');
    process.exit(0);
  }

  try {
    const directories = ['src', 'api', 'scripts'];
    let allFiles: string[] = [];

    for (const dir of directories) {
      allFiles = allFiles.concat(getFiles(dir));
    }

    const coreFiles = allFiles.filter(
      (f) => f.includes('analyze-core') || f.includes('mcp-tools') || f.includes('server.ts'),
    );

    let codeContext = '';
    for (const file of coreFiles) {
      codeContext += `\n--- ${file} ---\n`;
      codeContext += fs.readFileSync(file, 'utf-8');
    }

    const ai = new GoogleGenAI({ apiKey });

    const prompt = `
    You are an expert AI software architect for the Intelli-Credit Terminal open-source repository.
    Your task is to analyze the core files of the repository and generate an architectural summary.

    Here is the core code context:
    ${codeContext}

    Generate a detailed Markdown document that explains the architecture, the key components,
    how data flows through the system, and any major dependencies.
    Output only the Markdown document.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    if (response.text) {
      const outDir = 'docs/architecture';
      fs.mkdirSync(outDir, { recursive: true });
      fs.writeFileSync(path.join(outDir, 'ARCHITECTURE_SUMMARY.md'), response.text);
      console.info('Architecture summary generated successfully.');
    } else {
      console.warn('No response text generated by Gemini.');
    }
  } catch (err) {
    console.error('Error during repo analysis:', err);
    process.exit(1);
  }
}

void analyze();
