import * as fs from 'node:fs';
import { GoogleGenAI } from '@google/genai';

async function analyze(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return;
  }

  const ai = new GoogleGenAI({ apiKey });

  let graphData = '';
  try {
    graphData = fs.readFileSync('docs/architecture/knowledge-graph.json', 'utf-8');
  } catch {
    // Ignore if it doesn't exist yet
  }

  const prompt = `
You are the lead AI architect for Intelli-Credit Terminal.
Here is the dependency graph of the codebase generated by madge:
${graphData}

Please generate an overview of the architecture based on this graph. Output a markdown file that summarizes the core modules and their relationships.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    fs.mkdirSync('docs/architecture', { recursive: true });
    fs.writeFileSync('docs/architecture/ARCHITECTURE_OVERVIEW.md', response.text || '');
  } catch {
    // Ignore error
  }
}

await analyze().catch(() => {
  process.exit(1);
});
