import * as fs from 'node:fs';
import * as path from 'node:path';

function analyzeRepo(): void {
  console.info('Starting Repository Analysis...');
  const outDir = path.join('docs', 'architecture');
  fs.mkdirSync(outDir, { recursive: true });

  const summary = {
    analyzedAt: new Date().toISOString(),
    directories: [] as string[],
    note: 'This file is a placeholder overview. Detailed dependency graphs are generated by madge.',
  };

  const rootDirs = fs
    .readdirSync('.', { withFileTypes: true })
    .filter(
      (dirent) =>
        dirent.isDirectory() && !dirent.name.startsWith('.') && dirent.name !== 'node_modules',
    )
    .map((dirent) => dirent.name);

  summary.directories = rootDirs;

  const outPath = path.join(outDir, 'repo-analysis.json');
  fs.writeFileSync(outPath, JSON.stringify(summary, null, 2));
  console.info(`Repository analysis saved to ${outPath}`);
}

analyzeRepo();
