import { writeFileSync } from 'node:fs';

function generateDiagrams() {
  console.info('Generating architecture diagrams...');

  const mermaidDiagram = `# Intelli-Credit Architecture

This diagram is auto-generated by \`npm run generate:diagrams\`.

\`\`\`mermaid
graph TD
    A[React Client] -->|API Requests| B(Express Server)
    B -->|SDK Calls| C{Google Gemini API}
    C -->|Responses| B
    B -->|JSON/Data| A
\`\`\`
`;

  try {
    writeFileSync('docs/architecture.md', mermaidDiagram);
    console.info('Architecture diagram saved to docs/architecture.md');
  } catch (error) {
    console.error('Failed to write architecture diagram:', error);
  }
}

generateDiagrams();
