import fs from 'node:fs';
import path from 'node:path';
import { GoogleGenAI } from '@google/genai';

function getFiles(dirPath: string): string[] {
  const files: string[] = [];
  try {
    const items = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const item of items) {
      if (item.name === 'node_modules' || item.name === 'dist' || item.name === '.git') continue;
      const fullPath = path.join(dirPath, item.name);
      if (item.isDirectory()) {
        files.push(...getFiles(fullPath));
      } else if (fullPath.endsWith('.ts') || fullPath.endsWith('.tsx')) {
        files.push(fullPath);
      }
    }
  } catch (err) {
    console.warn(`Could not read directory: ${dirPath}`, err);
  }
  return files;
}

async function generateKnowledgeGraph() {
  console.info('Generating Knowledge Graph...');
  fs.mkdirSync('docs/architecture', { recursive: true });

  if (!process.env.GEMINI_API_KEY) {
    console.warn('GEMINI_API_KEY not found. Skipping Knowledge Graph generation.');
    process.exit(0);
  }

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

  let repoContext = '';
  const directoriesToScan = ['src', 'api', 'scripts'];
  for (const dir of directoriesToScan) {
    const files = getFiles(dir);
    for (const file of files) {
      try {
        const content = fs.readFileSync(file, 'utf8');
        repoContext += `\n--- File: ${file} ---\n${content}\n`;
      } catch (err) {
        console.error(`Failed to read ${file}`, err);
      }
    }
  }

  const prompt = `You are an expert system architect analyzing an open source project.
Analyze the provided codebase and generate a comprehensive "Knowledge Graph" document mapping out the core entities, modules, components, APIs, and their relationships.
Output the result in Markdown format. The document should act as a central hub for contributors to understand how different parts of the system interact.

Codebase Context:
${repoContext.substring(0, 100000)}
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const report = response.text;
    if (report) {
      fs.writeFileSync('docs/architecture/knowledge-graph.md', report, 'utf8');
      console.info('Knowledge graph generated at docs/architecture/knowledge-graph.md');
    } else {
      console.error('No text generated by Gemini API.');
    }
  } catch (err) {
    console.error('Error during Knowledge Graph generation:', err);
    process.exit(1);
  }
}

void generateKnowledgeGraph();
