import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';

const main = async () => {
  console.log('Running Continuous Improvement Analysis...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping real improvement analysis.');
    fs.writeFileSync(
      path.resolve(process.cwd(), 'docs/tech-debt-report.md'),
      '# Continuous Improvement Report\n\nGEMINI_API_KEY is not set. Skipping real improvement analysis.',
    );
    return;
  }

  const metadataPath = path.resolve(process.cwd(), 'metadata.json');
  let metadata: any = {};
  if (fs.existsSync(metadataPath)) {
    metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
You are an expert AI software architect and open-source maintainer.
Analyze the following repository metadata to identify technical debt, missing documentation, potential security risks, and areas for improvement.

Repository Metadata:
Name: ${metadata.name || 'Unknown'}
Description: ${metadata.description || 'Unknown'}
Frameworks: ${metadata.frameworks?.join(', ') || 'None'}
Dependencies: ${Object.keys(metadata.dependencies || {}).join(', ')}

Directory Structure Snippet:
${JSON.stringify(metadata.structure?.src || {}, null, 2).substring(0, 5000)}

Tasks:
1. Identify potential technical debt based on the stack and structure.
2. Suggest 3 concrete ways to improve the contributor experience.
3. Recommend any modernizations or dependency updates.
4. Highlight missing testing areas based on standard practices for this stack.
5. Provide actionable steps for the maintainers to resolve these issues.

Format your output as a Markdown report.
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'AI Generation failed due to an API error.';
  }

  const outDir = path.resolve(process.cwd(), 'docs');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const reportContent = `# Technical Debt & Repository Improvement Report
Date: ${new Date().toISOString()}

${responseText}
`;

  fs.writeFileSync(path.join(outDir, `tech-debt-report.md`), reportContent);

  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, reportContent);
  }

  console.log('Improvement report generated successfully.');
};

main().catch(console.error);
