import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';

const main = async () => {
  console.log('Running AI Repo Improvement Analyzer...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping real improvement generation.');
    return;
  }

  const metadataPath = path.resolve(process.cwd(), 'metadata.json');
  let metadata: any = {};
  if (fs.existsSync(metadataPath)) {
    metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
You are a Staff AI Software Engineer tasked with continuous improvement of a repository.
Analyze the following repository metadata to detect technical debt, code smells, architecture concerns, and identify refactoring opportunities.

Repository Metadata:
${JSON.stringify(metadata, null, 2).substring(0, 50000)}

Tasks:
1. Identify any missing modern tools or outdated dependencies.
2. Suggest improvements for the repository structure.
3. Highlight potential technical debt areas.
4. Recommend actionable steps for maintainers to improve code quality, security, and performance.
5. Propose 2-3 specific refactoring targets.

Format the output as a Markdown report.
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'AI Generation failed due to an API error.';
  }

  const outDir = path.resolve(process.cwd(), 'docs/improvements');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const reportContent = `# Repository Improvement Report
Date: ${new Date().toISOString()}

${responseText}
`;

  fs.writeFileSync(path.join(outDir, `report-${Date.now()}.md`), reportContent);
  fs.writeFileSync(path.join(outDir, 'latest-report.md'), reportContent);

  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, reportContent);
  }

  console.log('Improvement report generated successfully.');
};

main().catch(console.error);
