import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';

const main = async () => {
  console.log('Running AI Technical Debt Analyzer...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping real AI generation.');
    fs.mkdirSync(path.resolve(process.cwd(), 'docs'), { recursive: true });
    fs.writeFileSync(
      path.resolve(process.cwd(), 'docs/technical-debt-report.md'),
      'GEMINI_API_KEY is not set. Skipping real AI generation.'
    );
    return;
  }

  const ai = new GoogleGenAI({ apiKey });

  // Gather basic metadata and some source files
  const metadataPath = path.resolve(process.cwd(), 'metadata.json');
  let metadata: any = {};
  if (fs.existsSync(metadataPath)) {
    metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  }

  // We read server.ts and one component just to have a sample
  let sampleCode = '';
  const serverPath = path.resolve(process.cwd(), 'server.ts');
  if (fs.existsSync(serverPath)) {
    sampleCode += `\n\n--- server.ts ---\n` + fs.readFileSync(serverPath, 'utf8').substring(0, 5000);
  }

  const prompt = `
You are an expert AI software architect. Analyze the following project information and code samples for Technical Debt, Code Smells, and Optimization Opportunities.

Repository Name: ${metadata.name || 'Unknown Project'}
Dependencies: ${metadata.dependencies ? Object.keys(metadata.dependencies).join(', ') : 'Unknown'}

Sample Code:
${sampleCode}

Tasks:
1. Identify potential technical debt and code smells.
2. Provide specific, actionable refactoring recommendations.
3. Suggest ways to improve repository automation, testing, or documentation.

Output a Markdown report with sections: "Technical Debt", "Refactoring Opportunities", "Automation & Testing Gaps".
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'AI Generation failed due to an API error.';
  }

  const outDir = path.resolve(process.cwd(), 'docs');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const reportContent = `# Technical Debt & Repository Improvement Report
Date: ${new Date().toISOString()}

${responseText}
`;

  fs.writeFileSync(path.join(outDir, 'technical-debt-report.md'), reportContent);
  console.log('Technical Debt Report generated successfully at docs/technical-debt-report.md');
};

main().catch(console.error);
