import { GoogleGenAI } from '@google/genai';
import fs from 'fs';
import path from 'path';

const main = async () => {
  console.log('Running AI Issue Triager...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping AI triage generation.');
    return;
  }

  const issueTitle = process.env.ISSUE_TITLE || '';
  const issueBody = process.env.ISSUE_BODY || '';
  const issueNumber = process.env.ISSUE_NUMBER || 'UNKNOWN';

  if (!issueTitle && !issueBody) {
    console.warn('No issue title or body provided via environment variables.');
    return;
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
You are an expert AI issue triager and senior engineer for this project.
Analyze the following newly opened issue.

Title: ${issueTitle}
Body:
${issueBody}

Tasks:
1. Identify the core problem or request.
2. Determine if this is a Bug, Feature Request, Documentation issue, or Question.
3. Suggest a priority level (High, Medium, Low).
4. Provide a helpful initial response to the user. If it's a bug, suggest potential areas in the codebase to investigate or ask for specific missing information (like logs or reproduction steps). If it's a feature, discuss its feasibility or implementation approach.

Output your response in Markdown format, structured as follows:
### AI Triage Analysis
**Category:** [Category]
**Suggested Priority:** [Priority]

**Initial Assessment & Recommendations:**
[Your detailed response and recommendations here]
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'AI Generation failed due to an API error.';
  }

  const outPath = path.resolve(process.cwd(), 'ai-triage-output.md');
  fs.writeFileSync(outPath, responseText);

  console.log('AI Triage generated successfully.');
};

main().catch(console.error);
