import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';

const main = async () => {
  console.info('Running AI Issue Manager...');

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. Skipping real AI issue management.');
    fs.writeFileSync(
      path.resolve(process.cwd(), 'issue-response.md'),
      'GEMINI_API_KEY is not set. Skipping AI response.',
    );
    fs.writeFileSync(path.resolve(process.cwd(), 'issue-labels.txt'), 'needs-triage');
    return;
  }

  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath || !fs.existsSync(eventPath)) {
    console.warn('GITHUB_EVENT_PATH is not set or file does not exist. Skipping.');
    return;
  }

  const eventPayload = JSON.parse(fs.readFileSync(eventPath, 'utf8'));
  const issue = eventPayload.issue;
  if (!issue) {
    console.warn('No issue found in event payload. Skipping.');
    return;
  }

  const title = issue.title || '';
  const body = issue.body || '';

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
You are an expert AI software maintainer for an open-source project.
Analyze the following new issue.

Issue Title: ${title}
Issue Body:
${body}

Tasks:
1. Categorize the issue and provide exactly ONE or TWO comma-separated labels from the following list: 'bug', 'enhancement', 'question', 'documentation', 'needs-triage'. Output this on the very first line of your response in the format "LABELS: label1, label2".
2. Provide a helpful, welcoming initial response to the user. If it's a bug, suggest potential debugging steps or ask for missing information (like OS, browser, reproducible example). If it's a feature request, discuss architectural implications or alternative approaches. Be polite and professional.

Format:
LABELS: label1, label2
<Your helpful response here>
`;

  let responseText = '';
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    responseText = response.text || 'No response generated by AI.';
  } catch (error) {
    console.error('AI Generation failed:', error);
    responseText = 'AI Generation failed due to an API error.';
  }

  const lines = responseText.split('\n');
  let labels = 'needs-triage';
  let comment = responseText;

  if (lines[0].startsWith('LABELS:')) {
    labels = lines[0].replace('LABELS:', '').trim();
    comment = lines.slice(1).join('\n').trim();
  }

  fs.writeFileSync(path.resolve(process.cwd(), 'issue-response.md'), comment);
  fs.writeFileSync(path.resolve(process.cwd(), 'issue-labels.txt'), labels);

  console.info('AI Issue response generated successfully.');
};

main().catch(console.error);
