name: Links Checker

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 0 * * 1'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html'
          fail: false

      - name: Create Issue From Failures
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: '🔗 Broken Links Detected'
          content-filepath: ./lychee/out.md
          labels: 'documentation, bug'
